# Generated by Django 4.2.7 on 2023-12-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
